apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          #image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              #value: k8s-sigs.io/nfs-subdir-external-provisioner
              value: example.com/nfs
            - name: NFS_SERVER
              value: 192.168.101.136
            - name: NFS_PATH
              value: /mnt/nfs/promdata
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.101.136
            path: /mnt/nfs/promdata
